services:
#  stocks.api:
#    image: stocks.api
#    build:
#      context: .
#      dockerfile: Services/Stocks/Stocks.API/Dockerfile
  
  stocks.db:
    image: postgres
    container_name: stocks.db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=StocksDb
    restart: always
    ports:
      - "5432:5432"
        
  messageBroker:
    image: rabbitmq:management
    container_name: rabbitmq
    hostname: stock-tracker-mq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672" 